############################################## - âš“ï¸ é”šç‚¹åŒºå¼€å§‹ - ##############################################
# é”šç‚¹ - è¿œç¨‹è®¢é˜…ç»„
PProviders: &PProviders {type: http, interval: 86400, health-check: {enable: true, url: 'https://www.gstatic.com/generate_204', interval: 300}, filter: '^(?!.*(ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))'}
# é”šç‚¹ - ç­›é€‰ç»„ 
FilterHK: &FilterHK '(?i)æ¸¯|é¦™æ¸¯|ğŸ‡­ğŸ‡°|HK|Hong|HKG'
FilterTW: &FilterTW '(?i)å°|å°æ¹¾|ğŸ‡¼ğŸ‡¸|ğŸ‡¹ğŸ‡¼|TW|tai|TPE|TSA|KHH'
FilterSG: &FilterSG '(?i)æ–°|æ–°åŠ å¡|ğŸ‡¸ğŸ‡¬|SG|Sing|SIN|XSP'
FilterJP: &FilterJP '(?i)æ—¥|æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|Japan|NRT|HND|KIX|CTS|FUK'
FilterKR: &FilterKR '(?i)éŸ©|éŸ©å›½|ğŸ‡°ğŸ‡·|éŸ“|éŸ“åœ‹|é¦–å°”|å—æœé²œ|KR|KOR|Korea|South'
FilterUS: &FilterUS '(?i)ç¾|ç¾å›½|ğŸ‡ºğŸ‡¸|US|USA|JFK|LAX|ORD|ATL|DFW|SFO|MIA|SEA|IAD'
FilterEU: &FilterEU '(?i)(ğŸ‡§ğŸ‡ª|ğŸ‡¨ğŸ‡¿|ğŸ‡©ğŸ‡°|ğŸ‡«ğŸ‡®|ğŸ‡«ğŸ‡·|ğŸ‡©ğŸ‡ª|ğŸ‡®ğŸ‡ª|ğŸ‡®ğŸ‡¹|ğŸ‡±ğŸ‡¹|ğŸ‡±ğŸ‡º|ğŸ‡³ğŸ‡±|ğŸ‡µğŸ‡±|ğŸ‡¸ğŸ‡ª|ğŸ‡¬ğŸ‡§|CDG|FRA|AMS|MAD|BCN|FCO|MUC|BRU)'
FilterOther: &FilterOther '^(?!.*(ç›´è¿|æ¸¯|å°|æ–°|æ—¥|éŸ©|é¦™æ¸¯|å°æ¹¾|æ–°åŠ å¡|æ—¥æœ¬|éŸ©å›½|ç¾å›½|ğŸ‡­ğŸ‡°|ğŸ‡¼ğŸ‡¸|ğŸ‡¹ğŸ‡¼|ğŸ‡¸ğŸ‡¬|ğŸ‡¯ğŸ‡µ|ğŸ‡°ğŸ‡·|ğŸ‡ºğŸ‡¸|ğŸ‡¬ğŸ‡§|ğŸ‡¦ğŸ‡¹|ğŸ‡§ğŸ‡ª|ğŸ‡¨ğŸ‡¿|ğŸ‡©ğŸ‡°|ğŸ‡«ğŸ‡®|ğŸ‡«ğŸ‡·|ğŸ‡©ğŸ‡ª|ğŸ‡®ğŸ‡ª|ğŸ‡®ğŸ‡¹|ğŸ‡±ğŸ‡¹|ğŸ‡±ğŸ‡º|ğŸ‡³ğŸ‡±|ğŸ‡µğŸ‡±|ğŸ‡¸ğŸ‡ª|HK|TW|SG|JP|KR|US|GB|CDG|FRA|AMS|MAD|BCN|FCO|MUC|BRU|HKG|TPE|TSA|KHH|SIN|XSP|NRT|HND|KIX|CTS|FUK|JFK|LAX|ORD|ATL|DFW|SFO|MIA|SEA|IAD|LHR|LGW))'
FilterAll: &FilterAll '^(?!.*(ç›´è¿|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))'
# é”šç‚¹ - ç­–ç•¥ç»„
UrlTest: &UrlTest {type: url-test, interval: 60, tolerance: 20, lazy: true, url: 'https://www.gstatic.com/generate_204', disable-udp: false, timeout: 2000, max-failed-times: 3, hidden: true, include-all: true}
# é”šç‚¹ - é€‰æ‹©ç»„ 
T1: &T1 {type: select, proxies: [é¦™æ¸¯, æ—¥æœ¬, ç‹®åŸ, å°æ¹¾, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ, å†·é—¨, æ‰‹åŠ¨, ç›´è¿]}
T2: &T2 {type: select, proxies: [ç›´è¿, é¦™æ¸¯, æ—¥æœ¬, ç‹®åŸ, å°æ¹¾, ç¾å›½, éŸ©å›½, æ¬§ç›Ÿ, å†·é—¨, æ‰‹åŠ¨]}
# é”šç‚¹ - è§„åˆ™é›†
DomainMrs: &DomainMrs {type: http, interval: 86400, behavior: domain, format: mrs}
DomainText: &DomainText {type: http, interval: 86400, behavior: domain, format: text}
IPcidrMrs: &IPcidrMrs {type: http, interval: 86400, behavior: ipcidr, format: mrs}
IPcidrText: &IPcidrText {type: http, interval: 86400, behavior: ipcidr, format: text}
ClassicalText: &ClassicalText {type: http, interval: 86400, behavior: classical, format: text}
############################################## - âš“ï¸ é”šç‚¹åŒºç»“æŸ - ############################################## 

# è®¢é˜…
proxy-providers:
  æœºåœºA: {<<: *PProviders, url: 'æœºåœºè®¢é˜…åœ°å€', override: {additional-prefix: '[A] '}}
  æœºåœºB: {<<: *PProviders, url: 'æœºåœºè®¢é˜…åœ°å€', override: {additional-prefix: '[B] '}}

# æœ¬åœ°è‡ªå»ºèŠ‚ç‚¹ç»„
proxies:
  - {name: ç›´è¿, type: direct, udp: true}
# ç­–ç•¥ç»„ 
proxy-groups:
  - {name: ğŸš€ Proxy, <<: *T1}
  - {name: âœˆï¸ Telegram, <<: *T1}
  - {name: ğŸ¤– OpenAi, <<: *T1}
  - {name: ğŸ“ºï¸ YouTube, <<: *T1}
  - {name: ğŸ“½ï¸ Streaming, <<: *T1}
  - {name: ğŸ“» Spotify, <<: *T2}
  - {name: ğŸï¸ Emby&Game, <<: *T2}
  - {name: ğŸ“ SpeedTest, <<: *T2}  
  # åœ°åŒºç­–ç•¥
  - {name: é¦™æ¸¯, type: select, proxies: [é¦™æ¸¯è‡ªåŠ¨], include-all: true, filter: *FilterHK}
  - {name: æ—¥æœ¬, type: select, proxies: [æ—¥æœ¬è‡ªåŠ¨], include-all: true, filter: *FilterJP}
  - {name: ç‹®åŸ, type: select, proxies: [ç‹®åŸè‡ªåŠ¨], include-all: true, filter: *FilterSG}
  - {name: å°æ¹¾, type: select, proxies: [å°æ¹¾è‡ªåŠ¨], include-all: true, filter: *FilterTW}
  - {name: ç¾å›½, type: select, proxies: [ç¾å›½è‡ªåŠ¨], include-all: true, filter: *FilterUS}
  - {name: éŸ©å›½, type: select, proxies: [éŸ©å›½è‡ªåŠ¨], include-all: true, filter: *FilterKR}
  - {name: æ¬§ç›Ÿ, type: select, proxies: [æ¬§ç›Ÿè‡ªåŠ¨], include-all: true, filter: *FilterEU}
  - {name: å†·é—¨, type: select, include-all: true, filter: *FilterOther}
  - {name: æ‰‹åŠ¨, type: select, include-all: true, filter: *FilterAll}
  - {name: âŒ›ï¸ Final, type: select, proxies: [ğŸš€ Proxy, ç›´è¿]}
  # è‡ªåŠ¨æµ‹é€Ÿ
  - {name: é¦™æ¸¯è‡ªåŠ¨, <<: *UrlTest, filter: *FilterHK}
  - {name: å°æ¹¾è‡ªåŠ¨, <<: *UrlTest, filter: *FilterTW}
  - {name: ç‹®åŸè‡ªåŠ¨, <<: *UrlTest, filter: *FilterSG}
  - {name: æ—¥æœ¬è‡ªåŠ¨, <<: *UrlTest, filter: *FilterJP}
  - {name: éŸ©å›½è‡ªåŠ¨, <<: *UrlTest, filter: *FilterKR}
  - {name: ç¾å›½è‡ªåŠ¨, <<: *UrlTest, filter: *FilterUS}
  - {name: æ¬§ç›Ÿè‡ªåŠ¨, <<: *UrlTest, filter: *FilterEU}

# è¿œç¨‹è§„åˆ™é›†
rule-providers: 
  fix-direct:
    <<: *ClassicalText
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/fix-direct.list
  speedtest:
    <<: *ClassicalText
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/speedtest.list 
  emby:
    <: *ClassicalText
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/emby.list   
  openai:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/openai.mrs
  telegram:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/telegram.mrs
  instagram:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/instagram.mrs
  youtube:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/youtube.mrs
  spotify:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/spotify.mrs
  netflix:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/netflix.mrs
  disney:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/disney.mrs
  hbo:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/hbo.mrs
  tiktok:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/tiktok.mrs
  github:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/github.mrs
  onedrive:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/onedrive.mrs
  microsoft@cn:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/microsoft@cn.mrs
  microsoft:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/microsoft.mrs
  facebook:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/facebook.mrs
  meta:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/meta.mrs
  google:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/google.mrs
  apple-cn:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/apple-cn.mrs
  apple:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/apple.mrs
  cloudflare-cn:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/cloudflare-cn.mrs
  category-public-tracker:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/category-public-tracker.mrs
  category-games:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/category-games.mrs
  category-media-cn:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/category-media-cn.mrs
  category-media:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/category-media.mrs
  category-cryptocurrency:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/category-cryptocurrency.mrs
  category-social-media-!cn:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/category-social-media-!cn.mrs
  category-ai-chat-!cn:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/category-ai-chat-!cn.mrs
  geolocation-!cn:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/geolocation-!cn.mrs
  private_domain:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/private.mrs
  cn_domain:
    <<: *DomainMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/cn.mrs
  # IPç±»
  google_ip:
    <<: *IPcidrMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/google_ip.mrs
  netflix_ip:
    <<: *IPcidrMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/netflix_ip.mrs
  telegram_ip:
    <<: *IPcidrMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/telegram_ip.mrs
  private_ip:
    <<: *IPcidrMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/private_ip.mrs
  cn_ip:
    <<: *IPcidrMrs
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/cn_ip.mrs

rules:
  - RULE-SET,category-public-tracker,REJECT-DROP
  - RULE-SET,fix-direct,ç›´è¿
  - RULE-SET,private_ip,ç›´è¿,no-resolve
  - RULE-SET,speedtest,ğŸ“ SpeedTest
  - RULE-SET,openai,ğŸ¤– OpenAi
  - RULE-SET,category-ai-chat-!cn,ğŸ¤– OpenAi
  - RULE-SET,telegram,âœˆï¸ Telegram
  - RULE-SET,emby,ğŸï¸ Emby&Game
  - RULE-SET,youtube,ğŸ“ºï¸ YouTube
  - RULE-SET,spotify,ğŸ“» Spotify
  - RULE-SET,netflix,ğŸ“½ï¸ Streaming
  - RULE-SET,disney,ğŸ“½ï¸ Streaming
  - RULE-SET,hbo,ğŸ“½ï¸ Streaming
  - RULE-SET,tiktok,ğŸ“½ï¸ Streaming
  - RULE-SET,instagram,ğŸ“½ï¸ Streaming
  - RULE-SET,meta,ğŸ“½ï¸ Streaming
  - RULE-SET,github,ğŸš€ Proxy
  - RULE-SET,onedrive,ç›´è¿
  - RULE-SET,microsoft@cn,ç›´è¿
  - RULE-SET,microsoft,ç›´è¿
  - RULE-SET,google,ğŸš€ Proxy
  - RULE-SET,apple-cn,ç›´è¿
  - RULE-SET,apple,ç›´è¿
  - RULE-SET,cloudflare-cn,ç›´è¿
  - RULE-SET,category-media-cn,ç›´è¿
  - RULE-SET,category-games,ğŸï¸ Emby&Game
  - RULE-SET,category-media,ğŸš€ Proxy
  - RULE-SET,category-social-media-!cn,ğŸš€ Proxy
  - RULE-SET,cn_domain,ç›´è¿
  - RULE-SET,geolocation-!cn,ğŸš€ Proxy
  # è§„åˆ™é›†IPè§„åˆ™
  - RULE-SET,google_ip,ğŸš€ Proxy,no-resolve
  - RULE-SET,netflix_ip,ğŸ“½ï¸ Streaming,no-resolve
  - RULE-SET,telegram_ip,âœˆï¸ Telegram,no-resolve
  - RULE-SET,cn_ip,ç›´è¿,no-resolve
  - MATCH,âŒ›ï¸ Final

# å…¨å±€é…ç½®
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
unified-delay: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome
allow-lan: true
bind-address: '*'
mode: rule
log-level: warning
ipv6: true
udp: true
keep-alive-idle: 600
keep-alive-interval: 15

# å¤–éƒ¨æ§åˆ¶ (API)
external-controller: 0.0.0.0:9090
external-ui-url: https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
external-ui: ui
external-ui-name: metacubexd
secret: 123456

# è‡ªå®š GEO ä¸‹è½½åœ°å€
geox-url:
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  asn: https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb

# ç¼“å­˜
profile:
  store-selected: true
  store-fake-ip: true

# åŸŸåå—…æ¢
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - '+.v2ex.com'
  skip-domain:
    - 'rule-set:cn_domain,private_domain'
    - 'Mijia Cloud'
    - '+.push.apple.com'
    - '+.wechat.com'
    - '+.qpic.cn'
    - '+.qq.com'
    - '+.wechatapp.com'
    - '+.vivox.com'
    - '+.oray.com'
    - '+.sunlogin.net'
# Tun
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
# DNS
dns:
  enable: true
  ipv6: true
  respect-rules: false
  enhanced-mode: fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:cn_domain,private_domain"
    - "*"
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time-ios.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.qq.com"
    - "+.tencent.com"
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.cdn.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - na.b.g-tun.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - shark007.net
    - Mijia Cloud
    - "+.cmbchina.com"
    - "+.cmbimg.com"
    - local.adguard.org
    - "+.sandai.net"
    - "+.n0808.com"
    - "+.uu.163.com"
    - ps.res.netease.com
    - "+.gitv.tv"
    - "config.ptmi.gitv.tv"
    - "+.cnmmb.xyz"
    - "+.docker.io"
    - "+.miwifi.com"
    - "+.safebrowsing.apple"
    - "+.mihomos.us.kg"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  use-system-hosts: false
  use-hosts: false

