############################################## - âš“ï¸ é”šç‚¹åŒºå¼€å§‹ - ##############################################
# é”šç‚¹ - è¿œç¨‹è®¢é˜…ç»„
PP: &PP {type: http, interval: 86400, health-check: {enable: true, url: 'https://www.gstatic.com/generate_204', interval: 600}}
# é”šç‚¹ - ç­›é€‰ç»„ 
HK: &HK '(?i)æ¸¯|hk|hongkong|hong kong'
TW: &TW '(?i)å°|tw-|taiwan|tai wan'
SG: &SG '(?i)æ–°åŠ å¡|sg|singapore|ç‹®åŸ'
JP: &JP '(?i)æ—¥æœ¬|jp|japan'
US: &US '(?i)ç¾|us|unitedstates|united states'
OR: &OR '(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates)).*'
# é”šç‚¹ - ç­–ç•¥ç»„
UT: &UT {type: url-test, interval: 600, tolerance: 100, lazy: true, url: 'https://www.gstatic.com/generate_204', hidden: true, include-all: true}
# é”šç‚¹ - é€‰æ‹©ç»„ 
T1: &T1 {type: select, proxies: [é¦™æ¸¯, æ—¥æœ¬, ç‹®åŸ, å°æ¹¾, ç¾å›½, å…¶ä»–]}
T2: &T2 {type: select, proxies: [å›½å†…, é¦™æ¸¯, æ—¥æœ¬, ç‹®åŸ, å°æ¹¾, ç¾å›½, å…¶ä»–]}
T3: &T3 {type: select, proxies: [ğŸš€ Proxy, å›½å†…]}
# é”šç‚¹ - è§„åˆ™é›†
DMrs: &DMrs {type: http, interval: 86400, behavior: domain, format: mrs}
DText: &DText {type: http, interval: 86400, behavior: domain, format: text}
IMrs: &IMrs {type: http, interval: 86400, behavior: ipcidr, format: mrs}
IText: &IText {type: http, interval: 86400, behavior: ipcidr, format: text}
CText: &CText {type: http, interval: 86400, behavior: classical, format: text}
############################################## - âš“ï¸ é”šç‚¹åŒºç»“æŸ - ############################################## 
# è¿œç¨‹è®¢é˜…ç»„
proxy-providers:
  æœºåœºA: {<<: *PProviders, url: 'æœºåœºè®¢é˜…åœ°å€', override: {additional-prefix: '[A] '}}
  æœºåœºB: {<<: *PProviders, url: 'æœºåœºè®¢é˜…åœ°å€', override: {additional-prefix: '[B] '}}
# æœ¬åœ°è‡ªå»ºèŠ‚ç‚¹ç»„
proxies:
  - {name: å›½å†…, type: direct, udp: true}
# ç­–ç•¥ç»„ 
proxy-groups:
  - {name: ğŸš€ Proxy, <<: *T1}
  - {name: âœˆï¸ Telegram, <<: *T1}
  - {name: ğŸ¤– OpenAi, <<: *T1}
  - {name: ğŸ“ºï¸ YouTube, <<: *T1}
  - {name: ğŸ“½ï¸ Streaming, <<: *T1}
  - {name: ğŸ“» Spotify, <<: *T2}
  - {name: ğŸï¸ Emby&Game, <<: *T2}
  - {name: ğŸ“ SpeedTest, <<: *T2}
# åœ°åŒºç­–ç•¥
  - {name: é¦™æ¸¯, type: select, proxies: [é¦™æ¸¯è‡ªåŠ¨], include-all: true, filter: *HK}
  - {name: å°æ¹¾, type: select, proxies: [å°æ¹¾è‡ªåŠ¨], include-all: true, filter: *TW}
  - {name: ç‹®åŸ, type: select, proxies: [ç‹®åŸè‡ªåŠ¨], include-all: true, filter: *SG}
  - {name: æ—¥æœ¬, type: select, proxies: [æ—¥æœ¬è‡ªåŠ¨], include-all: true, filter: *JP}
  - {name: ç¾å›½, type: select, proxies: [ç¾å›½è‡ªåŠ¨], include-all: true, filter: *US}
  - {name: å…¶ä»–, type: select, proxies: [å…¶ä»–è‡ªåŠ¨], include-all: true, filter: *OR}
  - {name: æœªåŒ¹é…, <<: *T3}
# è‡ªåŠ¨æµ‹é€Ÿ
  - {name: é¦™æ¸¯è‡ªåŠ¨, <<: *UT, filter: *HK}
  - {name: å°æ¹¾è‡ªåŠ¨, <<: *UT, filter: *TW}
  - {name: ç‹®åŸè‡ªåŠ¨, <<: *UT, filter: *SG}
  - {name: æ—¥æœ¬è‡ªåŠ¨, <<: *UT, filter: *JP}
  - {name: ç¾å›½è‡ªåŠ¨, <<: *UT, filter: *US}
  - {name: å…¶ä»–è‡ªåŠ¨, <<: *UT, filter: *OR}

# è¿œç¨‹è§„åˆ™é›†
rule-providers: 
  fakeip-filter:
    <<: *DMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/fakeip-filter.mrs
  fix-direct:
    <<: *CText
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/fix-direct.list
  Speedtest:
    <<: *CText
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/networktest.list
  Emby:
    <<: *CText
    url: https://mirror.ghproxy.com/https://github.com/666OS/YYDS/raw/main/mihomo/rules/emby.list
  OpenAi:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.mrs
  Ai-chat:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-chat-!cn.mrs
  Telegram:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/telegram.mrs
  instagram:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/instagram.mrs
  Meta:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/meta.mrs
  YouTube:
    <<: *DMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/youtube.mrs
  Spotify:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/spotify.mrs
  Netflix:
    <<: *DMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/netflix.mrs
  Disney:
    <<: *DMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/disney.mrs
  HBO:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/hbo.mrs
  TikTok:
    <<: *DMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/tiktok.mrs
  Github:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.mrs
  Onedrive:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/onedrive.mrs
  Microsoft@cn:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft@cn.mrs
  Microsoft:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs
  Google:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs
  Apple-cn:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-cn.mrs
  Apple:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.mrs
  Cloudflare-cn:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cloudflare-cn.mrs
  Category-games:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-games.mrs
  Category-media-cn:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-media-cn.mrs
  Category-media:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-media.mrs
  Category-social-media-!cn:
    <<: *DMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-social-media-!cn.mrs
  Proxy:
    <<: *DMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/proxy.mrs
  private_domain:
    <<: *DMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/private.mrs
  cn_domain:
    <<: *DMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/cn.mrs
# IPç±»
  Google_ip:
    <<: *IMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs
  Netflix_ip:
    <<: *IMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/netflixip.mrs
  Telegram_ip:
    <<: *IMrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs
  Private_ip:
    <<: *IMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/privateip.mrs
  cn_ip:
    <<: *IMrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/clash-ruleset/cnip.mrs

rules:
  - RULE-SET,fix-direct,å›½å†…
  - RULE-SET,Private_ip,å›½å†…,no-resolve
  - RULE-SET,Speedtest,ğŸ“ SpeedTest
  - RULE-SET,OpenAi,ğŸ¤– OpenAi
  - RULE-SET,Ai-chat,ğŸ¤– OpenAi
  - RULE-SET,Telegram,âœˆï¸ Telegram
  - RULE-SET,Emby,ğŸï¸ Emby&Game
  - RULE-SET,YouTube,ğŸ“ºï¸ YouTube
  - RULE-SET,Spotify,ğŸ“» Spotify
  - RULE-SET,Netflix,ğŸ“½ï¸ Streaming
  - RULE-SET,Disney,ğŸ“½ï¸ Streaming
  - RULE-SET,HBO,ğŸ“½ï¸ Streaming
  - RULE-SET,TikTok,ğŸ“½ï¸ Streaming
  - RULE-SET,instagram,ğŸ“½ï¸ Streaming
  - RULE-SET,Github,ğŸš€ Proxy
  - RULE-SET,Google,ğŸš€ Proxy
  - RULE-SET,Meta,ğŸš€ Proxy
  - RULE-SET,Onedrive,å›½å†…
  - RULE-SET,Microsoft@cn,å›½å†…
  - RULE-SET,Microsoft,å›½å†…
  - RULE-SET,Apple-cn,å›½å†…
  - RULE-SET,Apple,å›½å†…
  - RULE-SET,Cloudflare-cn,å›½å†…
  - RULE-SET,Category-games,ğŸï¸ Emby&Game
  - RULE-SET,Category-media-cn,å›½å†…
  - RULE-SET,Category-media,ğŸš€ Proxy
  - RULE-SET,Category-social-media-!cn,ğŸš€ Proxy
  - RULE-SET,cn_domain,å›½å†…
  - RULE-SET,Proxy,ğŸš€ Proxy
# IP è§„åˆ™
  - RULE-SET,Google_ip,ğŸš€ Proxy,no-resolve
  - RULE-SET,Netflix_ip,ğŸ“½ï¸ Streaming,no-resolve
  - RULE-SET,Telegram_ip,âœˆï¸ Telegram,no-resolve
  - RULE-SET,cn_ip,å›½å†…
  - MATCH,æœªåŒ¹é…

# å…¨å±€é…ç½®
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
unified-delay: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
udp: true
keep-alive-idle: 600 
keep-alive-interval: 30
# å¤–éƒ¨æ§åˆ¶ (API)
external-controller: 0.0.0.0:9090
external-ui-url: https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
external-ui: ui
external-ui-name: metacubexd
secret: 123456
# è‡ªå®š GEO ä¸‹è½½åœ°å€
geox-url:
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  asn: https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
# ç¼“å­˜
profile:
  store-selected: true
  store-fake-ip: true
# åŸŸåå—…æ¢
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - '+.v2ex.com'
  skip-domain:
    - 'rule-set:cn_domain,private_domain'
    - 'Mijia Cloud'
    - '+.push.apple.com'
    - '+.wechat.com'
    - '+.qpic.cn'
    - '+.qq.com'
    - '+.wechatapp.com'
    - '+.vivox.com'
    - '+.oray.com'
    - '+.sunlogin.net'
# è™šæ‹Ÿç½‘å¡æ¨¡å¼
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
# DNS è®¾ç½®
dns:
  enable: true
  ipv6: true
  respect-rules: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:cn_domain,private_domain,fakeip-filter"
# DNS æœåŠ¡å™¨
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy:
    "rule-set:cn_domain,private_domain":
    - 223.5.5.5
    - 119.29.29.29
    "rule-set:Proxy":
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"

